
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class AplikasiKonversiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiKonversiSuhuh
     */
    public AplikasiKonversiSuhu() {
        initComponents();
        
        rbManual.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMode = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblInput = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        lblDari = new javax.swing.JLabel();
        cmbDari = new javax.swing.JComboBox<>();
        lblKe = new javax.swing.JLabel();
        cmbKe = new javax.swing.JComboBox<>();
        lblHasil = new javax.swing.JLabel();
        txtHasil = new javax.swing.JTextField();
        rbManual = new javax.swing.JRadioButton();
        rbOtomatis = new javax.swing.JRadioButton();
        btnKonversi = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(49, 49, 49));

        jLabel1.setFont(new java.awt.Font("Poppins Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplikasi Konversi Suhu");

        lblInput.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        lblInput.setForeground(new java.awt.Color(255, 255, 255));
        lblInput.setText("Masukkan Suhu :");

        txtInput.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        txtInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInputKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputKeyTyped(evt);
            }
        });

        lblDari.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        lblDari.setForeground(new java.awt.Color(255, 255, 255));
        lblDari.setText("Dari Skala :");

        cmbDari.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        cmbDari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Reamur", "Kelvin" }));
        cmbDari.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDariItemStateChanged(evt);
            }
        });

        lblKe.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        lblKe.setForeground(new java.awt.Color(255, 255, 255));
        lblKe.setText("Ke Skala :");

        cmbKe.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        cmbKe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Reamur", "Kelvin" }));
        cmbKe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbKeItemStateChanged(evt);
            }
        });

        lblHasil.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        lblHasil.setForeground(new java.awt.Color(255, 255, 255));
        lblHasil.setText("Hasil :");

        txtHasil.setEditable(false);
        txtHasil.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        txtHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHasilActionPerformed(evt);
            }
        });

        bgMode.add(rbManual);
        rbManual.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        rbManual.setForeground(new java.awt.Color(255, 255, 255));
        rbManual.setText("Manual");
        rbManual.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbManualItemStateChanged(evt);
            }
        });

        bgMode.add(rbOtomatis);
        rbOtomatis.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        rbOtomatis.setForeground(new java.awt.Color(255, 255, 255));
        rbOtomatis.setText("Otomatis");
        rbOtomatis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbOtomatisItemStateChanged(evt);
            }
        });

        btnKonversi.setBackground(new java.awt.Color(49, 49, 49));
        btnKonversi.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        btnKonversi.setForeground(new java.awt.Color(255, 255, 255));
        btnKonversi.setText("Konversi");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(49, 49, 49));
        btnKeluar.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblInput)
                                    .addComponent(lblDari, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblKe, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtInput)
                                    .addComponent(cmbDari, 0, 186, Short.MAX_VALUE)
                                    .addComponent(cmbKe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHasil)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rbManual, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbOtomatis, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnKonversi, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInput)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDari)
                    .addComponent(cmbDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKe)
                    .addComponent(cmbKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHasil)
                    .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbManual)
                    .addComponent(rbOtomatis))
                .addGap(34, 34, 34)
                .addComponent(btnKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void txtHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHasilActionPerformed

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
        try {
        double nilai = Double.parseDouble(txtInput.getText());
        String dari = cmbDari.getSelectedItem().toString();
        String ke = cmbKe.getSelectedItem().toString();
        
         if (dari.equals(ke)) {
            JOptionPane.showMessageDialog(this,
                    "Skala suhu 'Dari' dan 'Ke' tidak boleh sama!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return; // hentikan proses konversi
        }
         
        double hasil = 0;

        
        
        // Konversi Celcius ke lainnya
        if (dari.equals("Celcius")) {
            switch (ke) {
                case "Fahrenheit":
                    hasil = (nilai * 9/5) + 32;
                    break;
                case "Reamur":
                    hasil = nilai * 4/5;
                    break;
                case "Kelvin":
                    hasil = nilai + 273.15;
                    break;
                default:
                    hasil = nilai;
            }
        }

        // Konversi Fahrenheit ke lainnya
        else if (dari.equals("Fahrenheit")) {
            switch (ke) {
                case "Celcius":
                    hasil = (nilai - 32) * 5/9;
                    break;
                case "Reamur":
                    hasil = (nilai - 32) * 4/9;
                    break;
                case "Kelvin":
                    hasil = ((nilai - 32) * 5/9) + 273.15;
                    break;
                default:
                    hasil = nilai;
            }
        }

        // Tambahkan logika untuk Reamur dan Kelvin
        else if (dari.equals("Reamur")) {
            switch (ke) {
                case "Celcius":
                    hasil = nilai * 5/4;
                    break;
                case "Fahrenheit":
                    hasil = (nilai * 9/4) + 32;
                    break;
                case "Kelvin":
                    hasil = (nilai * 5/4) + 273.15;
                    break;
                default:
                    hasil = nilai;
            }
        } else if (dari.equals("Kelvin")) {
            switch (ke) {
                case "Celcius":
                    hasil = nilai - 273.15;
                    break;
                case "Fahrenheit":
                    hasil = ((nilai - 273.15) * 9/5) + 32;
                    break;
                case "Reamur":
                    hasil = (nilai - 273.15) * 4/5;
                    break;
                default:
                    hasil = nilai;
            }
        }

        txtHasil.setText(String.format("%.2f", hasil));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan nilai suhu yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnKonversiActionPerformed

    private void txtInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.') {
                evt.consume(); // Menolak input non-angka
        }          // TODO add your handling code here:
    }//GEN-LAST:event_txtInputKeyTyped

    private void txtInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyReleased
        if (rbOtomatis.isSelected()) {
        btnKonversiActionPerformed(null);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputKeyReleased

    private void rbManualItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbManualItemStateChanged
        if (rbManual.isSelected()) {
        btnKonversi.setEnabled(true); // mode manual, tombol bisa diklik
    }        // TODO add your handling code here:
    }//GEN-LAST:event_rbManualItemStateChanged

    private void rbOtomatisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbOtomatisItemStateChanged
        if (rbOtomatis.isSelected()) {
        btnKonversi.setEnabled(false); // mode otomatis, tombol dinonaktifkan
    }        // TODO add your handling code here:
    }//GEN-LAST:event_rbOtomatisItemStateChanged

    private void cmbDariItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDariItemStateChanged
        if (rbOtomatis.isSelected() && evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        btnKonversiActionPerformed(null);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDariItemStateChanged

    private void cmbKeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbKeItemStateChanged
        if (rbOtomatis.isSelected() && evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        btnKonversiActionPerformed(null);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKeItemStateChanged

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgMode;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKonversi;
    private javax.swing.JComboBox<String> cmbDari;
    private javax.swing.JComboBox<String> cmbKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDari;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblInput;
    private javax.swing.JLabel lblKe;
    private javax.swing.JRadioButton rbManual;
    private javax.swing.JRadioButton rbOtomatis;
    private javax.swing.JTextField txtHasil;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
